name: Test App
# name: Test, Build and Release apk
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: 'Run flutter pub get'
      run: flutter pub get
    - name: Enable flutter web
      run: flutter config --enable-web
    - name: 'Format code'
      run: dart format --set-exit-if-changed .
    - name: 'Run Test'
      run: flutter test
